---
zabbix_repo:
  name: 'zabbix-release'
  uri: '{{ "https://repo.zabbix.com/zabbix/" + agent_major_version | string + "/"
          + ("ubuntu-arm64" if ansible_architecture == "aarch64" else "ubuntu")
          + "/pool/main/z/zabbix-release/zabbix-release_latest%2B"
          + ansible_distribution | lower + ansible_distribution_version + "_all.deb" }}'
  # uri: '{{ "https://repo.zabbix.com/zabbix/" + agent_major_version | string + "/"
  #         + ("ubuntu-arm64" if ansible_architecture == "aarch64" else "ubuntu")
  #         + "/pool/main/z/zabbix-release/zabbix-release_"
  #         + agent_major_version | string + "-" + release_version[agent_major_version | string][ansible_architecture][ansible_distribution | lower] | string
  #         + "%2B" + ansible_distribution | lower + ansible_distribution_version + "_all.deb" }}'

zabbix_agent_package_list:
  - zabbix-sender
  - zabbix-get
  - 'zabbix-agent{{ "2" if agent_variant | string == "2" else "" }}'
