---
run_host_tasks: false
############################################################################################################################################
# zabbix_host_hostgroups: '{{ group_names + ["SUper GROUP"] }}'
zabbix_host_templates: ["Linux by Zabbix agent"]
# zabbix_host_templates: ["Linux by Zabbix agent active"]
zabbix_host_host_name: '{{ inventory_hostname }}'
zabbix_host_tags: '{{ [{"tag": "variant", "value": agent_variant},{"tag": "managed"}] }}'
zabbix_host_interfaces:
  - type: agent
    ip: '{{ ansible_host if ansible_host | ansible.utils.ipaddr else omit }}'
    dns: '{{ ansible_host if not ansible_host | ansible.utils.ipaddr else omit }}'
    useip: '{{ true if ansible_host | ansible.utils.ipaddr else false }}'
    port: '{{ ext_agent_port if (agent_variant is not defined or agent_variant | string == "1") else ext_agent_port2 }}'
