---
- name: 'Prepare containers'
  hosts: all
  pre_tasks:

    #     - name: "Prepare containers : logrotate for {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
    #       ansible.builtin.package:
    #         name:
    #           - logrotate
    #         state: present
    #       when: ansible_distribution == 'RedHat'

    - name: 'Prepare containers : epel for {{ ansible_distribution + ": " + ansible_distribution_major_version }}'
      # for package priority tests
      ansible.builtin.yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
        state: present
        disable_gpg_check: true
      when: ansible_distribution == 'RedHat'

    - name: 'Prepare containers : ca-certificates for {{ ansible_distribution + ": " + ansible_distribution_major_version }}'
      # ubuntu containers lack root CA
      ansible.builtin.package:
        name:
          - ca-certificates
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: 'Prepare containers : rsync, vim'
      ansible.builtin.package:
        name:
          - rsync
          - vim
        state: present

    - name: 'Prepare containers : firewalld'
      ansible.builtin.package:
        name:
          - firewalld
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: 'Prepare containers : firewalld enable'
      ansible.builtin.systemd:
        name: firewalld
        enabled: true
        state: started
      when: ansible_distribution == 'Ubuntu'
