- name: 'Zabbix API block'
  when: run_host_tasks is defined and run_host_tasks or "host" in ansible_run_tags
  throttle: 1
  delegate_to: '{{ zabbix_api_host }}'
  vars:
    ansible_connection: httpapi
    ansible_network_os: zabbix.zabbix.zabbix
    ansible_httpapi_port: '{{ zabbix_api_port }}' # if no port specified?
    ansible_user: '{{ zabbix_api_user if zabbix_api_token is not defined else omit }}'
    ansible_httpapi_pass: '{{ zabbix_api_password if zabbix_api_token is not defined else omit }}'
    ansible_httpapi_use_ssl: '{{ zabbix_api_use_ssl | default("False") }}'
    ansible_httpapi_validate_certs: '{{ zabbix_api_validate_certs | default("False") }}'
  tags: [host]
  block:
    - name: 'Zabbix API : Hostgroup presence'
      when: >-
        "remove" not in ansible_run_tags
      zabbix.zabbix.zabbix_hostgroup:
        name: '{{ zabbix_host_hostgroups }}'
        state: present
    - name: 'Zabbix API : Host presence'
      zabbix.zabbix.zabbix_host:
        state: '{{ "absent" if "remove" in ansible_run_tags else "present" }}'
        host_name: '{{ zabbix_host_host_name }}'
        visible_name: '{{ zabbix_host_visible_name | default(omit) }}'
        description: '{{ zabbix_host_description | default(omit) }}'
        hostgroups: '{{ zabbix_host_hostgroups }}'
        templates: '{{ zabbix_host_templates | default(omit) }}'
        interfaces: '{{ zabbix_host_interfaces | default(omit) }}'
        ipmi_authtype: '{{ zabbix_host_ipmi_authtype | default(omit) }}'
        ipmi_privilege: '{{ zabbix_host_ipmi_privilege | default(omit) }}'
        ipmi_username: '{{ zabbix_host_ipmi_username | default(omit) }}'
        ipmi_password: '{{ zabbix_host_ipmi_password | default(omit) }}'
        tls_accept: '{{ zabbix_host_tls_accept }}'
        tls_connect: '{{ zabbix_host_tls_connect }}'
        ### pskidentity is set in defaults. omitting when not needed.
        tls_psk_identity: '{{ zabbix_host_tls_psk_identity if zabbix_host_tls_connect == "psk" or "psk" in zabbix_host_tls_accept else omit }}'
        tls_psk: '{{ zabbix_agent_psk_value | default(omit) }}'
        tls_issuer: '{{ zabbix_host_tls_issuer | default(omit) }}'
        tls_subject: '{{ zabbix_host_tls_subject | default(omit) }}'
        tags: '{{ zabbix_host_tags | default(omit) }}'
        macros: '{{ zabbix_host_macros | default(omit) }}'
        inventory_mode: '{{ zabbix_host_inventory_mode | default(omit) }}'
        inventory: '{{ zabbix_host_inventory | default(omit) }}'
        status: '{{ zabbix_host_status | default(omit) }}'
        proxy: '{{ zabbix_host_proxy | default(omit) }}'
