---
- name: 'Semanage: Add port to "zabbix_agent_port_t" type'
  become: true
  when: >-
    param_listenport is defined and param_listenport | int != 10050
    and ansible_selinux.status is defined and ansible_selinux.status == "enabled"
    and (ansible_selinux.mode is defined and ansible_selinux.mode == "enforcing"
        or ansible_selinux.config_mode is defined and ansible_selinux.config_mode == "enforcing")
  ansible.builtin.command: >-
    semanage port -a -t zabbix_agent_port_t -p tcp {{ param_listenport }}
  register: semanage_result
  changed_when: >-
    semanage_result.rc | int == 0 and
    (semanage_result.stdout + semanage_result.stderr) == ""
  failed_when: >-
    semanage_result.rc | int == 1 and
    (semanage_result.stdout + semanage_result.stderr)
    | regex_search("already defined") is none
  tags: [selinux]
