---
- name: 'Semanage: Add port to "zabbix_agent_port_t" type'
  become: true
  when: >-
    param_listenport is defined and param_listenport | int != 10050
  ansible.builtin.command: >-
    semanage port -a -t zabbix_agent_port_t -p tcp {{ param_listenport }}
  register: semanage_result
  changed_when: >-
    semanage_result.rc | int == 0 and
    (semanage_result.stdout + semanage_result.stderr) == ""
  failed_when: >-
    semanage_result.rc | int == 1 and
    (semanage_result.stdout + semanage_result.stderr)
    | regex_search("already defined") is none
  tags: [selinux]

- name: 'Seboolean: zabbix_run_sudo'
  ansible.posix.seboolean:
    name: zabbix_run_sudo
    persistent: true
    state: true
  when:
    - seboolean_zabbix_run_sudo
  tags: [selinux]
